### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by jerry-sl** [Conflux-Chain/open-cfxmine#3]
` cmake -DCMAKE_BUILD_TYPE=Release -B build

-- JsonCpp Version: 1.9.3
CMake Error at third-party/jsoncpp/src/lib_json/CMakeLists.txt:93 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 7.5.0.

-- Configuring incomplete, errors occurred!
See also "/root/fic/open-cfxmine/build/CMakeFiles/CMakeOutput.log".
See also "/root/fic/open-cfxmine/build/CMakeFiles/CMakeError.log".`

Env:
 Ubuntu 18.04

How to fix this CMake error?  Any dependencies other than cuda, boost? thx

**Comment by ftiasch** [comment]
Could you please kindly provide "CMakeOutput.log" & "CMakeError.log", which helps us reproduce your errors? Thanks!
