### ISSUE TITLE
Insufficient memory on NVIDIA GeForce RTX 2060 SUPER

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/open-cfxmine#4]
![image](https://user-images.githubusercontent.com/7571518/97490905-c1455280-1961-11eb-964e-38f050531582.png)

**Comment by ftiasch** [comment]
Could you also provide the output of `nvidia-smi`?

**Comment by cryptoleekwu** [comment]
You can try a larger virtual memory setting

**Comment by Thegaram** [comment]
I opened this on behalf of a community member. Will close it for now, he/she can reopen if needed.
