### ISSUE TITLE
can not mine

### ISSUE THREAD

**Issue by zhanghaojia123456** [Conflux-Chain/open-cfxmine#5]
Start the miner for 127.0.0.1:32525
Press q and enter to quit the miner at any time.
Trying to connect to the server 127.0.0.1:32525
Unable to connect and subscribe to the server 127.0.0.1:32525!
Trying to connect to the server 127.0.0.1:32525
Unable to connect and subscribe to the server 127.0.0.1:32525!
Trying to connect to the server 127.0.0.1:32525
Unable to connect and subscribe to the server 127.0.0.1:32525!

**Comment by ftiasch** [comment]
You should have a full node running on `127.0.0.1:32525`, which can be downloaded from https://github.com/Conflux-Chain/conflux-rust/releases/tag/v1.0.0.
